# Generated by Django 5.2.4 on 2025-07-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_primer_app', '0005_celulares_heladeras_lavarropas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Televisores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=20)),
                ('fecha_publicación', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
